[project]
name = "mcp-practice"
version = "0.1.0"
description = "An MCP Practice project"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "anthropic>=0.60.0",
    "arxiv>=2.2.0",
    "mcp>=1.12.3",
    "nest-asyncio>=1.6.0",
    "openai>=1.98.0",
    "python-dotenv>=1.1.1",
]
